language: cpp
os: linux
dist: focal
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev
script:
  - cmake -DCMAKE_CXX_FLAGS=-Werror -DCMAKE_INSTALL_PREFIX=prefix -DSYSTEMWIDE=ON .
  - make
  - make install
